Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-063dd30adbb186909 # Amazon Linux AMI in N.California
      UserData:
        'Fn::Base64': 
          !Sub |
            #!/bin/bash
            yum -y update

            # install apache
            yum install httpd24 -y  
            
            # start server
            service httpd start
            chkconfig httpd on
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Type
          Value: Server Instance
